FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential \
    cmake \
    ninja-build \
    gdb \
    git \
    ccache \
    lcov \
    gcovr \
    pkg-config \
    libgtest-dev \
    redis-server \
    sudo \
    iproute2 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app