FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential \
    cmake \
    ninja-build \
    clang \
    clang-format \
    gdb \
    git \
    ccache \
    lcov \
    gcovr \
    pkg-config \
    sudo \
    iproute2 \
    iputils-ping \
    tcpdump \
    libcap-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

CMD ["bash"]